apiVersion: v2
name: pulseops-kibana
description: Standalone Kibana Chart for PulseOps
type: application
version: 0.1.0
appVersion: "8.5.1"
dependencies:
  - name: kibana
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: kibana.enabled