kibana:
  enabled: true
  replicas: 1
  elasticsearchHosts: "https://elasticsearch-master:9200"
  elasticsearchCertificateSecret: "elasticsearch-master-certs"
  elasticsearchCertificateAuthoritiesFile: "ca.crt"
  elasticsearchCredentialSecret: "elasticsearch-master-credentials"
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"