workers:
  payment:
    autoscaling:
      enabled: false
  inventory:
    autoscaling:
      enabled: false
  notification:
    autoscaling:
      enabled: false

api:
  serviceMonitor:
    enabled: false
  autoscaling:
    enabled: false

web:
  certificate:
    enabled: false
  autoscaling:
    enabled: false

workersMonitoring:
  enabled: false

kafka:
  serviceMonitor:
    enabled: false