apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: client
      targetPort: 9092
    - port: 9093
      name: controller
      targetPort: 9093
    - port: 9308
      name: metrics
      targetPort: 9308
  selector:
    app: kafka