kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      image:
        registry: quay.io
        repository: prometheus/prometheus
        tag: v2.54.1
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      retention: 3d
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

  alertmanager:
    enabled: true
    alertmanagerSpec:
      image:
        registry: quay.io
        repository: prometheus/alertmanager
        tag: v0.27.0
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi

  grafana:
    enabled: true
    adminPassword: "admin"
    image:
      repository: grafana/grafana
      tag: 11.2.0
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL

  nodeExporter:
    enabled: true

  prometheus-node-exporter:
    image:
      repository: prometheus/node-exporter
      tag: v1.8.2
      pullPolicy: IfNotPresent

  kubeStateMetrics:
    enabled: true

  kube-state-metrics:
    image:
      registry: registry.k8s.io
      repository: kube-state-metrics/kube-state-metrics
      tag: v2.13.0
      pullPolicy: IfNotPresent


eck-stack:
  enabled: true

  # Elasticsearch
  eck-elasticsearch:
    enabled: true
    fullnameOverride: elasticsearch

    nodeSets:
      - name: default
        count: 1

        config:
          node.store.allow_mmap: false

        resources:
          requests:
            cpu: "200m"
            memory: "1.2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"

        volumeClaimTemplates:
          - metadata:
              name: elasticsearch-data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi


  # Kibana
  eck-kibana:
    enabled: true
    count: 1

    elasticsearchRef:
      name: elasticsearch

    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"


  # Logstash
  eck-logstash:
    enabled: true
    fullnameOverride: logstash

    count: 1

    elasticsearchRefs:
      - name: elasticsearch
        clusterName: eck

    pipelines:
      - pipeline.id: pulseops
        config.string: |
          input {
            beats {
              port => 5044
            }
          }

          filter {
            json {
              source => "message"
              skip_on_invalid_json => true
            }
          }

          output {
            elasticsearch {
              hosts => [ "${ECK_ES_HOSTS}" ]
              user => "${ECK_ES_USER}"
              password => "${ECK_ES_PASSWORD}"
              ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
              index => "pulseops-logs-%{+YYYY.MM.dd}"
            }
          }

    services:
      - name: beats
        service:
          spec:
            type: ClusterIP
            ports:
              - name: beats
                port: 5044
                protocol: TCP
                targetPort: 5044

    podTemplate:
      spec:
        containers:
          - name: logstash
            resources:
              requests:
                cpu: "100m"
                memory: "512Mi"
              limits:
                cpu: "500m"
                memory: "1Gi"


  # Filebeat
  eck-beats:
    enabled: true

    type: filebeat

    daemonSet:
      podTemplate:
        spec:
          automountServiceAccountToken: true

          containers:
            - name: filebeat
              resources:
                requests:
                  cpu: "50m"
                  memory: "100Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"

              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName

              volumeMounts:
                - name: varlogpods
                  mountPath: /var/log/pods
                  readOnly: true

                - name: filebeat-data
                  mountPath: /usr/share/filebeat/data

          volumes:
            - name: varlogpods
              hostPath:
                path: /var/log/pods

            - name: filebeat-data
              emptyDir: {}

    config:
      filebeat.inputs:
        - type: container
          paths:
            - /var/log/pods/*/*/*.log

          processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                  - logs_path:
                      logs_path: "/var/log/pods/"

      output.logstash:
        hosts:
          - "logstash-ls-beats:5044"
