{{- if and .Values.api.serviceMonitor .Values.api.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api-monitor
  labels:
    app: pulseops-api
    release: observability
spec:
  selector:
    matchLabels:
      app: pulseops-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
{{- end }}