apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulseops-observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/mohammadhosein-p/PulseOps.git"
    targetRevision: main
    path: charts/observability
    helm:
      releaseName: observability
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true