apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulseops-kibana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ gitops_repo_url | default('https://github.com/<YOUR_USER>/<YOUR_REPO>.git') }}"
    targetRevision: main
    path: charts/kibana
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true