global:
  imageRegistry: ghcr.io
  imageOwner: mohammadhosein-p
  imagePullSecrets:
    - name: ghcr-secret

api:
  replicaCount: 1
  image:
    repository: ghcr.io/mohammadhosein-p/pulseops-api
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 4000
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

web:
  replicaCount: 1
  image:
    repository: ghcr.io/mohammadhosein-p/pulseops-web
    tag: "latest"
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

workers:
  payment:
    replicaCount: 1
    image:
      repository: ghcr.io/mohammadhosein-p/pulseops-payment-worker
      tag: "latest"
    processingDelayMs: 1500
    resources:
      limits:
        memory: 192Mi
      requests:
        memory: 96Mi

  inventory:
    replicaCount: 1
    image:
      repository: ghcr.io/mohammadhosein-p/pulseops-inventory-worker
      tag: "latest"
    processingDelayMs: 1000
    resources:
      limits:
        memory: 192Mi
      requests:
        memory: 96Mi

  notification:
    replicaCount: 1
    image:
      repository: ghcr.io/mohammadhosein-p/pulseops-notification-worker
      tag: "latest"
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 64Mi

postgresql:
  enabled: true
  auth:
    username: pulseops
    password: password
    database: pulseops_db
  primary:
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
    persistence:
      size: 1Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 64Mi
    persistence:
      size: 1Gi

kafka:
  enabled: true
  kraft:
    enabled: true
  zookeeper:
    enabled: false
  listeners:
    client:
      protocol: PLAINTEXT
  controller:
    replicaCount: 1
    resources:
      limits:
        memory: 768Mi
      requests:
        memory: 384Mi
    heapOpts: "-Xmx384m -Xms384m"
    persistence:
      size: 2Gi